spring:
  application:
    name: spring-aop

  datasource:
    password: 1
    url: jdbc:postgresql://localhost:5455/spring-data-demo
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8080